// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knwkeuqvzlgqkiqpesuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtud2tldXF2emxncWtpcXBlc3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTMyMTAsImV4cCI6MjA3Mzk4OTIxMH0.HKymtWGi7_IUfsn0GrR0ibxFrJXgQ5wPjI1AhAFFG2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});